# LeetCode Solutions
# Auto-generated by LeetCode Solution Saver


# Problem 1: Two Sum
# URL: https://leetcode.com/problems/two-sum/
# Date: 2025-08-26 17:32:19

def twoSum(nums, target):
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
    return []

# End of solution for Problem 1
==================================================




# Problem 2316: Count Hills and Valleys in an Array
# URL: https://leetcode.com/problems/count-hills-and-valleys-in-an-array/
# Date: 2025-08-26 22:46:07

class Solution:
    def countHillValley(self, nums: List[int]) -> int:
        c = 0
        i = 1
        while i != (len(nums) - 1):
            if nums[i-1] == nums[i]:
                nums.pop(i-1)
                i -= 1
            elif nums[i] == nums[i+1]:
                nums.pop(i)


# End of solution for Problem 2316
==================================================
# Problem 1302: Delete Characters to Make Fancy String
# URL: https://leetcode.com/problems/delete-characters-to-make-fancy-string/
# Date: 2025-08-26 18:02:10

        o.append(s[-1])
        return ''.join(o)

# End of solution for Problem 1302
==================================================

