# LeetCode Solutions
# Auto-generated by LeetCode Solution Saver


# Problem 1: Two Sum
# URL: https://leetcode.com/problems/two-sum/
# Date: 2025-08-26 17:32:19

def twoSum(nums, target):
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
    return []

# End of solution for Problem 1
==================================================





# Problem 2316: Count Hills and Valleys in an Array
# URL: https://leetcode.com/problems/count-hills-and-valleys-in-an-array/
# Date: 2025-08-26 23:17:17

class Solution:
    def countHillValley(self, nums: List[int]) -> int:
        c = 0
        i = 1
        while i != (len(nums) - 1):
            if nums[i-1] == nums[i]:
                nums.pop(i-1)
                i -= 1
            elif nums[i] == nums[i+1]:
                nums.pop(i)


# End of solution for Problem 2316
==================================================
# Problem 1302: Delete Characters to Make Fancy String
# URL: https://leetcode.com/problems/delete-characters-to-make-fancy-string/
# Date: 2025-08-26 23:13:57

class Solution:
    def makeFancyString(self, s: str) -> str:
        if len(s) < 3:
            return s
        o = [s[0]]
        for i in range(1, len(s)-1):
            if s[i-1] == s[i] == s[i+1]:
                next
            else:
                o.append(s[i])


# End of solution for Problem 1302
==================================================




# Problem 175: Combine Two Tables
# URL: https://leetcode.com/problems/combine-two-tables/
# Date: 2025-09-20 17:42:43

# Write your MySQL query statement below

SELECT p.firstName, p.lastName, a.city, a.state
FROM Person p
LEFT JOIN Address a ON p.personId = a.personId;

# End of solution for Problem 175
==================================================






# Problem 176: Second Highest Salary
# URL: https://leetcode.com/problems/second-highest-salary/
# Date: 2025-09-21 23:22:32

        return df
    else:
        df.loc[0] = ((sorted(salaries))[-2])
        return df

# End of solution for Problem 176
==================================================




# Problem 177: Nth Highest Salary
# URL: https://leetcode.com/problems/nth-highest-salary/
# Date: 2026-06-28 18:43:21

import pandas as pd

def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:

    unique_salaries = employee['salary'].drop_duplicates().sort_values(ascending=False)
    if len(unique_salaries) < N or N <= 0:
        return pd.DataFrame({f'getNthHighestSalary({N})': [None]})
    nth_salary = unique_salaries.iloc[N - 1]
    return pd.DataFrame({f'getNthHighestSalary({N})': [nth_salary]})


# End of solution for Problem 177
==================================================

